version: '3.4'

services:
  agent:
    image: mailproxee-agent
    environment:
     - Database:ConnectionString=Server=db;Database=mailproxee;User Id=mailproxee;Password=;
     - Mailbox:Domain=mailprivac.ee
     - Mailbox:IncomingPrefix=m
     - Mailbox:ReplyPrefix=reply
     - Mailbox:Host=localhost
     - Mailbox:ImapPort=993
     - Mailbox:SmtpPort=587
     - Mailbox:UserName=
     - Mailbox:Password=
    build:
      context: .
      dockerfile: MailProxee.Agent/Dockerfile
    depends_on:
     - db
    networks:
     - backend

  client:
    image: mailproxee-client
    environment:
     - VIRTUAL_HOST=mailprivac.ee
    build:
      context: .
      dockerfile: MailProxee.WebClient/Dockerfile
    depends_on:
     - db
    networks:
     - proxy
     - backend

  db:
    image: postgres:latest
    environment:
     - POSTGRES_DB=mailproxee
     - POSTGRES_PASSWORD=
    volumes:
     - mailproxee-db:/var/lib/postgresql/data
    networks:
     - backend

  proxy:
    image: jwilder/nginx-proxy
    ports:
     - 80:80
     - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
     - proxy

networks:
  proxy:
  backend:

volumes:
  mailproxee-db: